name: CI

# Run on pushes and PRs to any branch (adjust if you want only main)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    name: Test (node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'        # built-in npm caching

      - name: Install dependencies
        run: npm ci           # fast, reproducible install (requires package-lock.json)

      - name: Lint
        run: npm run lint     # optional - remove if you don't have lint script

      - name: Run tests
        run: npm test

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ./test-results || ./logs || ./coverage  # adjust to your output
